# Generated by Django 5.0.7 on 2024-08-05 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MemberLab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=20)),
                ('majors', models.TextField()),
                ('research_topic', models.TextField()),
            ],
        ),
    ]
